/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as IndexImport } from './routes/index';
import { Route as SectorIndexImport } from './routes/sector.$index';

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

const SectorIndexRoute = SectorIndexImport.update({
  id: '/sector/$index',
  path: '/sector/$index',
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/sector/$index': {
      id: '/sector/$index';
      path: '/sector/$index';
      fullPath: '/sector/$index';
      preLoaderRoute: typeof SectorIndexImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/sector/$index': typeof SectorIndexRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/sector/$index': typeof SectorIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/sector/$index': typeof SectorIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/sector/$index';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/sector/$index';
  id: '__root__' | '/' | '/sector/$index';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  SectorIndexRoute: typeof SectorIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SectorIndexRoute: SectorIndexRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/sector/$index"
      ]
    },
    "/": {
      "filePath": "index.ts"
    },
    "/sector/$index": {
      "filePath": "sector.$index.ts"
    }
  }
}
ROUTE_MANIFEST_END */
