/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as IndexImport } from './routes/index';
import { Route as SectorTitleImport } from './routes/sector.$title';

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

const SectorTitleRoute = SectorTitleImport.update({
  id: '/sector/$title',
  path: '/sector/$title',
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/sector/$title': {
      id: '/sector/$title';
      path: '/sector/$title';
      fullPath: '/sector/$title';
      preLoaderRoute: typeof SectorTitleImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/sector/$title': typeof SectorTitleRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/sector/$title': typeof SectorTitleRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/sector/$title': typeof SectorTitleRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/sector/$title';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/sector/$title';
  id: '__root__' | '/' | '/sector/$title';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  SectorTitleRoute: typeof SectorTitleRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SectorTitleRoute: SectorTitleRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/sector/$title"
      ]
    },
    "/": {
      "filePath": "index.ts"
    },
    "/sector/$title": {
      "filePath": "sector.$title.ts"
    }
  }
}
ROUTE_MANIFEST_END */
